"""Extraction against committed PDF fixtures.

Assertions here are deliberately coarse -- known substrings, page and column
counts, no undecodable glyphs -- and never exact whitespace or exact line
counts. pdfminer's line grouping shifts slightly between releases, and a test
that pins it turns a routine dependency bump into a mystery failure in a module
that did not change.

The fixtures are committed bytes, regenerated by hand with
``scripts/make_ingest_fixtures.py``. See that file for why they are not built
at test time.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from studio.ingest import pdf
from studio.ingest.pdf import ExtractionError, extract

FIXTURES = Path(__file__).resolve().parent.parent / "fixtures"


def load(name: str) -> bytes:
    return (FIXTURES / name).read_bytes()


@pytest.fixture(scope="module")
def single() -> pdf.Extraction:
    return extract(load("resume_single_column.pdf"))


@pytest.fixture(scope="module")
def two_column() -> pdf.Extraction:
    return extract(load("resume_two_column.pdf"))


class TestSingleColumn:
    def test_reads_the_whole_page(self, single: pdf.Extraction) -> None:
        assert single.pages == 1
        assert single.warnings == []
        for expected in (
            "Alex Morgan",
            "alex.morgan@example.com",
            "PROFESSIONAL EXPERIENCE",
            "Northwind Systems",
            "University of Texas at Austin",
            "PostgreSQL",
        ):
            assert expected in single.text

    def test_right_aligned_dates_do_not_make_it_two_column(
        self, single: pdf.Extraction
    ) -> None:
        """End to end, on a real PDF, of the layout the geometry tests cover."""
        assert single.columns == 1

    def test_a_date_is_never_fused_to_the_employer_beneath_it(
        self, single: pdf.Extraction
    ) -> None:
        """The failure this would cause is silent and reaches an employer."""
        texts = [line.text for line in single.lines]
        assert "Northwind Systems" in texts
        assert "Mar 2021 – Present" in texts

    def test_bullets_are_recognised_and_their_glyphs_removed(
        self, single: pdf.Extraction
    ) -> None:
        bullets = [line for line in single.lines if line.bullet]
        assert len(bullets) == 5
        assert all(not line.text.startswith(("•", "-", "*")) for line in bullets)
        assert any(line.text.startswith("Rebuilt the payments ledger") for line in bullets)

    def test_wrapped_bullets_are_rejoined(self, single: pdf.Extraction) -> None:
        """A wrapped bullet must arrive as one accomplishment, not two."""
        joined = [line for line in single.lines if "under three hours" in line.text]
        assert len(joined) == 1
        assert joined[0].text.startswith("Rebuilt the payments ledger")

    def test_headings_are_bold(self, single: pdf.Extraction) -> None:
        """The signal the segmenter leans on hardest."""
        headings = {
            line.text for line in single.lines if line.bold and line.text.isupper()
        }
        assert {"SUMMARY", "PROFESSIONAL EXPERIENCE", "EDUCATION"} <= headings

    def test_no_undecodable_glyphs(self, single: pdf.Extraction) -> None:
        assert "(cid:" not in single.text

    def test_typographic_characters_survive(self, single: pdf.Extraction) -> None:
        """An en-dash mangled into "?" turns a date range into nonsense."""
        assert "–" in single.text


class TestTwoColumn:
    def test_detects_the_second_column(self, two_column: pdf.Extraction) -> None:
        assert two_column.columns == 2

    def test_columns_are_read_in_full_not_interleaved(
        self, two_column: pdf.Extraction
    ) -> None:
        """A plain top-to-bottom sort would shuffle the sidebar into the body,
        splitting every job from the bullets underneath it."""
        texts = [line.text for line in two_column.lines]
        sidebar = texts.index("LANGUAGES")
        experience = texts.index("EXPERIENCE")
        assert sidebar < experience
        # Everything in the sidebar comes before anything in the main column.
        assert texts.index("Figma") < experience

    def test_a_capitalised_wrap_is_rejoined_by_its_indent(
        self, two_column: pdf.Extraction
    ) -> None:
        """"...brought the catalogue to" / "WCAG 2.1 AA" -- the case a
        lowercase-only continuation rule silently splits in two."""
        joined = [line for line in two_column.lines if "WCAG" in line.text]
        assert len(joined) == 1
        assert joined[0].text.startswith("Introduced accessibility auditing")

    def test_bullets_survive_the_column_split(self, two_column: pdf.Extraction) -> None:
        assert sum(1 for line in two_column.lines if line.bullet) == 7


class TestUnreadableFiles:
    def test_a_scan_is_reported_as_having_no_text_layer(self, monkeypatch) -> None:
        """Feeding an empty text layer to a model wastes a minute and returns
        nothing; the user needs to be told it was a scan."""
        monkeypatch.setattr(
            pdf,
            "read_pages",
            lambda data, **kwargs: [pdf.Page(number=1, x0=0.0, width=612.0, lines=[])],
        )
        with pytest.raises(ExtractionError) as caught:
            extract(b"%PDF-1.7 pretend")
        assert caught.value.code == "no_text_layer"

    def test_undecodable_fonts_are_reported_before_reaching_a_model(
        self, monkeypatch
    ) -> None:
        noise = [
            pdf.Line(text="(cid:12)(cid:15)(cid:9)(cid:22)" * 4, top=float(700 - i * 12))
            for i in range(30)
        ]
        monkeypatch.setattr(
            pdf,
            "read_pages",
            lambda data, **kwargs: [pdf.Page(number=1, x0=0.0, width=612.0, lines=noise)],
        )
        with pytest.raises(ExtractionError) as caught:
            extract(b"%PDF-1.7 pretend")
        assert caught.value.code == "undecodable"

    def test_a_non_pdf_is_rejected_rather_than_parsed(self) -> None:
        with pytest.raises(ExtractionError):
            extract(b"this is not a pdf, it is a sentence" * 20)


class TestLimits:
    def test_a_long_resume_is_truncated_on_a_line_boundary(self) -> None:
        """A model handed half a sentence will finish it, and invent whatever
        it needs to."""
        data = load("resume_single_column.pdf")
        result = extract(data, max_chars=300)
        assert len(result.text) <= 300
        assert result.warnings
        # Truncation never leaves a partial line behind.
        full = extract(data)
        assert all(line.text in {item.text for item in full.lines} for line in result.lines)


class TestTheWonkyResume:
    """A résumé built the way a template site builds one.

    Photo, coloured sidebar, skill meters, icon glyphs, tabular dates, and every
    heading set with `letter-spacing`. It is the shape of résumé this pipeline
    is least prepared for, and it is a common one.

    Before `unspace` this document produced **zero sections** -- twenty-seven
    lines swept into the contact block.
    """

    def _segments(self):
        from studio.ingest.pdf import extract
        from studio.ingest.segment import segment

        data = (FIXTURES / "resume_wonky.pdf").read_bytes()
        return segment(extract(data).lines)

    def test_its_sections_are_found(self) -> None:
        found = {segment.key for segment in self._segments()}

        assert {"contact", "skills", "experience", "education"} <= found

    def test_the_work_history_survives(self) -> None:
        """The thing that was being lost entirely."""
        experience = next(s for s in self._segments() if s.key == "experience")
        text = experience.text

        assert "Staff Frontend Engineer" in text
        assert "Fabrikam" in text
        assert "Frontend Engineer" in text
        assert "Tailspin Toys" in text
        # Every bullet, including the one glued to its employer line by the
        # table markup.
        assert "design system used by nine product teams" in text
        assert "first-contentful-paint" in text
        assert "visual regression testing" in text
        assert "checkout flow" in text
        assert "WCAG 2.1 AA" in text

    def test_the_sidebar_is_not_lost_to_the_main_column(self) -> None:
        skills = next(s for s in self._segments() if s.key == "skills")

        assert "TypeScript" in skills.text
        assert "Terraform" in skills.text
